before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: k6vuMRr2I1W/C7N5GX0D7VqQvAF6dWnuKsyevgioI/wIxAHBu+9t7ZCuKnEFmMezkb+HnB2lUZ6a7/0OKiPUFQ1XhbMUQtW8PDLs6Ru7QG3iKlkKtcPa9BxqeTt0Z/eAMQ7FKgU//6FRvxvOacT/RTmEz4yrmF7HzijFzeB/5/sxXtK9xJzsWfXlM4B/vniXm4635jWrBnqvQ+kIE2b1C1vw39avBbKTzaQMoDXhWfpeiPYfVgR6qJJSe80zPaLqBxrs8TnJPLKIbYykE0hBccdehUhlohtzNxZwmQ8A+oiAiJ6RJfS8qdLNFwx02iKPE1CGSHUApkRdfwSnqj3f9UJtzNEfMtLjkUmaMmUEGTGtF3xnlLhyn23xBqyhCtwPVGwRcz0mjOKOA6+djmH9LGKD8g5eV7k4inWcSX28I5FTq/s0OLOSLHYy3Pc4LvtYSirznluo8TVxsvwOlOBZjsaIZbpjVxzeliJldiwK0DWlVoy3j13nwg0bc1JgddCyHimUf4LRQMiKwwyKY6MWBz5pGNpxGpzhz/eHi5/e0u0pceKUcCwbGYn5Tp52rEAGMwsL4dU2Z4VdHYUXcA+Gv6/IzcONA9SzB8OL57assnYnP9yWBf3HZ/Km4u+QmZPJFVd7Fj2S/f2oC4ubIPps/JoqlBsK67jLH7GEV0wJmvQ= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml
    # - CRYPTO_AES_ENCRYPTED_SH: YjZiMmIwNjYyY2E0OGI5YjQ4ZmI3YTdkYmU4NjViN2I=I93wn43H8K4/eB5Wvi6A2irUFGh17rfCMer38OP/nGwK/4CqVaqXLLQlnG0aW/B+Zt+rUVfwxFxQplOTNqrK3WtMKw1307LZjVv/TPshn/uGxPUqpJTI075x+/b73WEYCXFvwCMwE1GVNiZTS8hGRmmhdLsFy7jlqQwGm0sp7VhUDRSmPsSH5rPplwKCvisqfcMBfCiGjfpXmrbX3gAnwDorfdHLKPFJlzUTcxPeEAjhT8pDckamS+V5scyCZwCqQdRFGOGva3KDyjBIOISbKkdhk1Yn8PczsJe7zrT+j2+mbBV32HPOQdmrwfPC/u3uLZSeTa+kob416KrOdHZWzk1p8DitQBgZUDwBd3ZVvxwc1lOrpciCunR3HXuaJIXKEkrzDu0V2uV/0V9vkeKFmFrTTnKad/4HPtB3GEfBkDPWEWOoYglEeIhMv5cBWdYnfFaV5Kkp145NI8IBQovJ07UyMk7uPcUEcY+V4s3RP3JZ2ZkfSOBXSMT5oa6m6DOX+w3ZNMsj4S0DYt/ncKvOOtqNOiXCChFGgwVd3hgfifgpiWF9CyqDL9AUkRgJyE9uFWccdPID8hw9hvHm1CinboH0CQZkX0/RbIy/R0S8nVS22HTX0SOgq6/yhacalRn6pkX1KxWgZc8gmgTlGvX/YcEzB31sQhy//jm69dd+XELcijk+jFmdf9jnW9Lyo366sRXXdnqFE5gDE4ZMOvyDyURDtKyBnaoy4FnMJY0HAfAIY46MN2/9ZKb9FQTigvVV # CRYPTO_AES_ENCRYPTED_SH
language:
    - node_js
node_js:
    # - 6
    - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
